enrichment/prismatic_ui/config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'home/index'

  devise_for :admin_users
  root "home#index"

end

enrichment/prismatic_ui/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,:registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

enrichment/prismatic_ui/app/models/event.rb
class Event < ActiveRecord::Base
  searchkick callbacks: :async
  def search_data
    as_json
  end
end

enrichment/prismatic_ui/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin_user!
  layout :layout_by_resource
   def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
    

  end 
end

enrichment/prismatic_ui/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("created_at DESC").page(params[:page]).per(10)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :object_id, :object_class, :user_id, :session_id, :page_url, :page_path, :page_referrer, :page_search, :user_agent, :ip, :country_code, :country_name, :region_code, :region_name, :city, :time_zone, :latitude, :longitude, :zip_code, :platform, :device, :browser, :device_id, :event_time, :action_class, :action_type)
    end
end

enrichment/prismatic_ui/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

enrichment/prismatic_ui/app/helpers/application_helper.rb
module ApplicationHelper
end

enrichment/prismatic_ui/app/helpers/events_helper.rb
module EventsHelper
end

enrichment/prismatic_ui/app/helpers/home_helper.rb
module HomeHelper
end

enrichment/prismatic_ui/app/views/application/_flash_message.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name.to_sym == :notice ? "success" : "error" %> alert-block fade in">
       <button data-dismiss="alert" class="close close-sm" type="button">
          <i class="fa fa-times"></i>
      </button>
      <%= content_tag :p, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>

enrichment/prismatic_ui/app/views/application/_footer.html.erb
 <!--footer start-->
 <footer class="site-footer">
  <div class="text-center">
    
    <a href="#" class="go-top">
      <i class="fa fa-angle-up"></i>
    </a>
  </div>
</footer>
      <!--footer end-->

enrichment/prismatic_ui/app/views/application/_header.html.erb
<header class="header white-bg">
  <div class="sidebar-toggle-box">
    <div data-original-title="Toggle Navigation" data-placement="right" class="fa fa-bars tooltips">
    </div>
  </div>
    <!--logo start-->
  <a href="<%= root_url%>" class="logo" >Prismatic<span>HQ</span></a>
  <!--logo end-->
  <div class="nav notify-row" id="top_menu">
    <!--  notification start -->
    <ul class="nav top-menu">
      <!-- settings start -->
     <!--  <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <i class="fa fa-tasks"></i>
          <span class="badge bg-success">6</span>
        </a>
        <ul class="dropdown-menu extended tasks-bar">
          <div class="notify-arrow notify-arrow-green"></div>
          <li>
            <p class="green">You have 6 pending tasks</p>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Dashboard v1.3</div>
                <div class="percent">40%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                  <span class="sr-only">40% Complete (success)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Database Update</div>
                <div class="percent">60%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                  <span class="sr-only">60% Complete (warning)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Iphone Development</div>
                <div class="percent">87%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 87%">
                  <span class="sr-only">87% Complete</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Mobile App</div>
                <div class="percent">33%</div>
              </div>
              <div class="progress progress-striped">
                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
                  <span class="sr-only">33% Complete (danger)</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="task-info">
                <div class="desc">Dashboard v1.3</div>
                <div class="percent">45%</div>
              </div>
              <div class="progress progress-striped active">
                <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                  <span class="sr-only">45% Complete</span>
                </div>
              </div>

            </a>
          </li>
          <li class="external">
            <a href="#">See All Tasks</a>
          </li>
        </ul>
      </li> -->
     <!-- settings end -->
      <!-- inbox dropdown start-->
     <!--  <li id="header_inbox_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-important">5</span>
        </a>
        <ul class="dropdown-menu extended inbox">
          <div class="notify-arrow notify-arrow-red"></div>
          <li>
            <p class="red">You have 5 new messages</p>
          </li>
          <li>
            <a href="#">
              <span class="photo"><%= image_tag "avatar-mini.jpg" %></span>
              <span class="subject">
                <span class="from">Jonathan Smith</span>
                <span class="time">Just now</span>
              </span>
              <span class="message">
                Hello, this is an example msg.
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="photo">
                <%= image_tag "avatar-mini2.jpg" %></span>
              <span class="subject">
                <span class="from">Jhon Doe</span>
                <span class="time">10 mins</span>
              </span>
              <span class="message">
               Hi, Jhon Doe Bhai how are you ?
             </span>
           </a>
          </li>
          <li>
            <a href="#">
              <span class="photo"><%= image_tag "avatar-mini3.jpg" %></span>
              <span class="subject">
                <span class="from">Jason Stathum</span>
                <span class="time">3 hrs</span>
              </span>
              <span class="message">
                This is awesome dashboard.
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="photo"><%= image_tag "avatar-mini4.jpg" %></span>
              <span class="subject">
                <span class="from">Jondi Rose</span>
                <span class="time">Just now</span>
              </span>
              <span class="message">
                Hello, this is metrolab
              </span>
            </a>
          </li>
          <li>
            <a href="#">See all messages</a>
          </li>
        </ul>
      </li> -->
      <!-- inbox dropdown end -->
      <!-- notification dropdown start-->
      <!-- <li id="header_notification_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

          <i class="fa fa-bell-o"></i>
          <span class="badge bg-warning">7</span>
        </a>
        <ul class="dropdown-menu extended notification">
          <div class="notify-arrow notify-arrow-yellow"></div>
          <li>
            <p class="yellow">You have 7 new notifications</p>
          </li>
          <li>
            <a href="#">
              <span class="label label-danger"><i class="fa fa-bolt"></i></span>
              Server #3 overloaded.
              <span class="small italic">34 mins</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-warning"><i class="fa fa-bell"></i></span>
              Server #10 not respoding.
              <span class="small italic">1 Hours</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-danger"><i class="fa fa-bolt"></i></span>
              Database overloaded 24%.
              <span class="small italic">4 hrs</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-success"><i class="fa fa-plus"></i></span>
              New user registered.
              <span class="small italic">Just now</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-info"><i class="fa fa-bullhorn"></i></span>
              Application error.
              <span class="small italic">10 mins</span>
            </a>
          </li>
          <li>
            <a href="#">See all notifications</a>
          </li>
        </ul>
      </li> -->
      <!-- notification dropdown end -->
    </ul>
  </div>
  <div class="top-nav ">
    <ul class="nav pull-right top-menu">
      <!-- <li>
        <input type="text" class="form-control search" placeholder="Search">
      </li> -->
      <!-- user login dropdown start-->
      <% if current_admin_user %>
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">            
            
            <span class="username"><%= current_admin_user.email%></span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu extended logout">
            <div class="log-arrow-up"></div>            
             
              <li><a href="<%#= settings_path %>"><i class="fa fa-cog"></i> Settings</a></li>
              <li><%= link_to '<i class="fa fa-power-off"></i> Logout'.html_safe, destroy_admin_user_session_path, :method=>'delete' %></li>            
          </ul>
        </li>
      <% end %>  
      <!-- user login dropdown end -->
    </ul>
  </div>
</header>

enrichment/prismatic_ui/app/views/application/_sidebar.html.erb
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu" id="nav-accordion">
      <li>
        <%=link_to "<span>Event<span>".html_safe, events_path%>
      </li> 
    


    </ul>
    <!-- sidebar menu end-->
  </div>
</aside>

enrichment/prismatic_ui/app/views/application/_slidebar.html.erb
<!-- Right Slidebar start -->
<div class="sb-slidebar sb-right sb-style-overlay">
  <h5 class="side-title">Online Customers</h5>
  <ul class="quick-chat-list">
    <li class="online">
      <div class="media">
        <a href="#" class="pull-left media-thumb">
          <img alt="" src="img/chat-avatar2.jpg" class="media-object">
        </a>
        <div class="media-body">
          <strong>John Doe</strong>
          <small>Dream Land, AU</small>
        </div>
      </div><!-- media -->
    </li>
    <li class="online">
      <div class="media">
        <a href="#" class="pull-left media-thumb">
          <img alt="" src="img/chat-avatar.jpg" class="media-object">
        </a>
        <div class="media-body">
          <div class="media-status">
            <span class=" badge bg-important">3</span>
          </div>
          <strong>Jonathan Smith</strong>
          <small>United States</small>
        </div>
      </div><!-- media -->
    </li>
    <li class="online">
      <div class="media">
        <a href="#" class="pull-left media-thumb">
          <img alt="" src="img/pro-ac-1.png" class="media-object">
        </a>
        <div class="media-body">
          <div class="media-status">
            <span class=" badge bg-success">5</span>
          </div>
          <strong>Jane Doe</strong>
          <small>ABC, USA</small>
        </div>
      </div><!-- media -->
    </li>
    <li class="online">
      <div class="media">
        <a href="#" class="pull-left media-thumb">
          <img alt="" src="img/avatar1.jpg" class="media-object">
        </a>
        <div class="media-body">
          <strong>Anjelina Joli</strong>
          <small>Fockland, UK</small>
        </div>
      </div><!-- media -->
    </li>
    <li class="online">
      <div class="media">
        <a href="#" class="pull-left media-thumb">
          <img alt="" src="img/mail-avatar.jpg" class="media-object">
        </a>
        <div class="media-body">
          <div class="media-status">
            <span class=" badge bg-warning">7</span>
          </div>
          <strong>Mr Tasi</strong>
          <small>Dream Land, USA</small>
        </div>
      </div><!-- media -->
    </li>
  </ul>
  <h5 class="side-title"> pending Task</h5>
  <ul class="p-task tasks-bar">
    <li>
      <a href="#">
        <div class="task-info">
          <div class="desc">Dashboard v1.3</div>
          <div class="percent">40%</div>
        </div>
        <div class="progress progress-striped">
          <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
            <span class="sr-only">40% Complete (success)</span>
          </div>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <div class="task-info">
          <div class="desc">Database Update</div>
          <div class="percent">60%</div>
        </div>
        <div class="progress progress-striped">
          <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
            <span class="sr-only">60% Complete (warning)</span>
          </div>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <div class="task-info">
          <div class="desc">Iphone Development</div>
          <div class="percent">87%</div>
        </div>
        <div class="progress progress-striped">
          <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
            <span class="sr-only">87% Complete</span>
          </div>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <div class="task-info">
          <div class="desc">Mobile App</div>
          <div class="percent">33%</div>
        </div>
        <div class="progress progress-striped">
          <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
            <span class="sr-only">33% Complete (danger)</span>
          </div>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <div class="task-info">
          <div class="desc">Dashboard v1.3</div>
          <div class="percent">45%</div>
        </div>
        <div class="progress progress-striped active">
          <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
            <span class="sr-only">45% Complete</span>
          </div>
        </div>

      </a>
    </li>
    <li class="external">
      <a href="#">See All Tasks</a>
    </li>
  </ul>
</div>
      <!-- Right Slidebar end -->

enrichment/prismatic_ui/app/views/events/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        Edit Event
      </header>
      <div class="panel-body">
       <%= render 'form' %>

      </div>
    </section>
  </div>
</div>

enrichment/prismatic_ui/app/views/events/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        Events
        <span class="pull-right">
          <%#= link_to '+ New Event', new_event_path ,:class=>"btn btn-primary"%>
        </span>  
      </header> 
      <div class="panel-body">
        <div class="adv-table">
          <table  class="display table table-bordered table-striped">
            <thead>

              <tr>
                <th>Event Name</th>
                <th>Object</th>
                <th>Object class</th>
                <th>User</th>
                <th>Session</th>
                
                <th>Event time</th>
                <th>Action class</th>
                <th>Action type</th>
                
              </tr>
            </thead>
            <tbody>
             <% @events.each do |event| %>
             <tr>
              <td><%=link_to event.event_name,event_path(event) %></td>
              <td><%= event.object_id %></td>
              <td><%= event.object_class %></td>
              <td><%= event.user_id %></td>
              <td><%= event.session_id %></td>
              <td><%= event.event_time %></td>
              <td><%= event.action_class %></td>
              <td><%= event.action_type %></td>

            </tr>
            <% end %>

 
          </tbody>
        </table>  
          <hr />
          <%= page_entries_info @events %> 
          <div class="pull-right pagination-wrapper">   
            <%= paginate @events %>
          </div>
      </div>
    </div>  
  </section> 
</div>
</div>    

enrichment/prismatic_ui/app/views/events/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        New Event
      </header>
      <div class="panel-body">
       <%= render 'form' %>

      </div>
    </section>
  </div>
</div>

enrichment/prismatic_ui/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        Event Information
      </header> 
      <div class="panel-body">
        <div class="adv-table">
          <table  class="display table table-bordered table-striped">
            <thead>

              <tr>
                <th>Event Name</th>
                <th>Object</th>
                <th>Object class</th>
                <th>Action Class</th>
                <th>Action type</th>
                <th>App ID</th>
                <th>App Name</th>
                <th>User ID</th>
                <th>Session ID</th>
                <th>Tracker Name</th>
                <th>Event Time</th>
                <th>Collector Event Time</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @event.event_name %></td>
                <td><%= @event.object_id %></td>
                <td><%= @event.object_class %></td>
                <td><%= @event.action_class %></td>
                <td><%= @event.action_type %></td>
                <td><%= @event.app_id %></td>
                <td><%= @event.app_name %></td>
                <td><%= @event.user_id %></td>
                <td><%= @event.session_id %></td>
                <td><%= @event.tracker_name %></td>
                <td><%= @event.event_time %></td>
                <td><%= @event.collector_event_time %></td>

              </tr>
            </tbody>
          </table>
          <header class="panel-heading">
            Page Information
          </header>
          <div class="panel-body">
            <div class="adv-table">
              <table class="display table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Page URL</th>
                    <th>Page Path</th>
                    <th>Page Referrer</th>
                    <th>Page Search</th>
                    <th>User Agent</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @event.page_url %></td>
                    <td><%= @event.page_path %></td>
                    <td><%= @event.page_referrer %></td>
                    <td><%= @event.page_search %></td>
                    <td><%= @event.user_agent %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
              <header class="panel-heading">
                Geo Information
              </header>
              <div class="panel-body">
                <div class="adv-table">
                <table class="display table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>IP Address</th>
                      <th>Country Code</th>
                      <th>Country Name</th>
                      <th>Region Code</th>
                      <th>Region Name</th>
                      <th>City</th>
                      <th>Time Zone</th>
                      <th>Latitude</th>
                      <th>Longitude</th>
                      <th>Zip Code</th>
                      <th>Platform</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><%= @event.ip_address %></td>
                      <td><%= @event.country_code %></td>
                      <td><%= @event.country_name %></td>
                      <td><%= @event.region_code %></td>
                      <td><%= @event.region_name %></td>
                      <td><%= @event.city %></td>
                      <td><%= @event.time_zone %></td>
                      <td><%= @event.latitude %></td>
                      <td><%= @event.longitude %></td>
                      <td><%= @event.zip_code %></td>
                      <td><%= @event.platform %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <header class="panel-heading">
              Device Information
            </header>
            <div class="panel-body">
              <div class="adv-table">
              <table class="display table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Device Name</th>
                    <th>Device Type</th>
                    <th>Browser</th>
                    <th>Screen Width</th>
                    <th>Screen Height</th>
                    <th>OS Name</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @event.device_name %></td>
                    <td><%= @event.device_type %></td>
                    <td><%= @event.browser %></td>
                    <td><%= @event.screen_width %></td>
                    <td><%= @event.screen_height %></td>
                    <td><%= @event.os_name %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <header class="panel-heading">
            Properties
          </header>
            <div class="panel-body">
              <div class="adv-table">
                <table class="display table table-bordered table-striped">
                  <thead>
                      <tr>
                        <% @event.properties.each_pair do |key,value| %>
                          <th> <%= key %> </th>
                        <% end %>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <% @event.properties.each_pair do |key,value| %>
                          <td> <%= value %> </td>
                        <% end %>
                      </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <%= link_to 'Edit', edit_event_path(@event) %> |
            <%= link_to 'Back', events_path %>
          </div>
        </div>
      </div>
    </div>
    </section>
  </div>
</div>

enrichment/prismatic_ui/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

enrichment/prismatic_ui/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Amar Daxini">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="img/favicon.png">
    <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic" /> -->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
  
    <title>PrismaticHQ</title>  

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>
      <section id="container" class="">
        <!--header start-->
        <%= render "header" %>
        <!--header end-->
        <!--sidebar start-->
        <%= render "sidebar" %>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
          <section class="wrapper site-min-height">
            <%= render :partial=>"flash_message" %>
            <!-- page start-->
            <%= yield %>
            <!-- page end-->
          </section>
        </section>
        <!--main content end-->
        <%#= render "slidebar" %>
        <!--footer start-->
        <%= render "footer" %>
        <%= yield :javascript%>
        <!--footer end-->
      </section>
    <!-- js placed at the end of the document so the pages load faster -->
   
    <!--common script for all pages-->
    
  </body>
</html>


 

enrichment/prismatic_ui/app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Amar Daxini">
    <meta name="keyword" content="Mock test,IIt Jee Preparation">
    <link rel="shortcut icon" href="img/favicon.png">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  
    <%= csrf_meta_tags %>
    <title>PrismaticHQ</title> 
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <![endif]-->
    </head>

  <body class="login-body">

    <%= yield %>

  </body>
</html>


 